baseURL = "https://112books.github.io/machiroku-web/"
defaultContentLanguage = "ca"
title = "Machiroku"

[taxonomies]
  category = "categories"
  tag = "tags"

[mediaTypes]
  [mediaTypes."text/yaml"]
    suffixes = ["yaml", "yml"]

[outputFormats]
  [outputFormats.YAML]
    mediaType = "text/yaml"
    isPlainText = true

[build]
  writeStats = true
