
baseURL = "https://example.com"
defaultContentLanguage = "ca"

[languages]
  [languages.ca]
    weight = 1
    languageName = "Català"
  [languages.es]
    weight = 2
    languageName = "Español"
  [languages.en]
    weight = 3
    languageName = "English"
