
backend:
  name: git-gateway

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "home"
    label: "Home"
    files:
      - file: "content/ca/_index.md"
        label: "Home CA"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
