repo: 112books/machiroku-web
branch: main
api_root: https://api.github.com

media_folder: static/images
public_folder: /images

collections:
  - name: pages
    label: Pàgines
    folder: content/ca
    create: true
    fields:
      - { name: title, label: Titol, widget: string }
      - { name: body, label: Contingut, widget: markdown }
