backend:
  name: github
  repo: 112books/machiroku-web
  branch: main
  base_url: https://machiroku.hola-78f.workers.dev

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pàgines"
    folder: "content/ca"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titol", name: "title", widget: "string" }
      - { label: "Contingut", name: "body", widget: "markdown" }
